services:
    
    flask-app:
        build:
            context: .
            dockerfile: dashboard/Dockerfile_dashboard  # Specify the unique Dockerfile name
        ports:
            - 8080:5000
        volumes:
            - ./dashboard:/app
            - ./data:/data
        environment:
            - NAME=Flask-App
            - PYTHONPATH=/app
            - DATABASE_URL=postgresql://student:infomdss@db_dashboard:5432/dashboard # Update to match our own db
        working_dir: /app
        depends_on:
            db_dashboard:
                condition: service_healthy

    
    db_dashboard:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=student
            - POSTGRES_PASSWORD=infomdss
            - POSTGRES_DB=dashboard
        volumes:
            - db_dashboard-data:/var/lib/postgresql/data/
        container_name: dss_group1_project
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U student -d dashboard -h localhost"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s

volumes:
    db_dashboard-data: